croque-scp/notifier

notifier/tasks.py
notifier/wikiconnection.py

The scope of this PR is to have the thing be able to send Wikidot messages via PM. Sending messages via email is out of scope.
While I'm here:

Send messages via PM

---

notifier/digest.py
notifier/formatter.py
notifier/lang.toml

I currently have formatting set up for PMs in Wikidot syntax. But I need emails as well.
I intended for the parts of the formatting file that have languages to be free of formatting, however, that's not the case. So it would be ideal to have some syntax that's neither Wikidot syntax nor HTML that can be converted to either. It doesn't need to be complicated, because I'm only using a tiny subset of either language. I can always add to it if other languages need more features.

Formatting for both PMs and emails

---

README.md
config.toml
notifier/__main__.py
notifier/config/tool.py
notifier/database/drivers/base.py
notifier/database/drivers/sqlite.py
notifier/database/queries/check_would_email.sql
notifier/digest.py
notifier/emailer.py
notifier/formatter.py
notifier/lang.toml
notifier/tasks.py
notifier/types.py
notifier/wikiconnection.py
pyproject.toml
tests/test_digest.py

For users for whom receiving Wikidot notifications is untenable (i.e. site administrators with lots of application notifications), emails are a useful alternative.

Send messages via email

---

notifier/database/drivers/base.py
notifier/database/drivers/sqlite.py
notifier/database/queries/create_tables.script.sql
notifier/database/queries/get_post_children.sql
notifier/database/queries/get_posts_in_subscribed_threads.sql
notifier/database/queries/get_replies_to_subscribed_posts.sql
notifier/database/queries/mark_thread_as_deleted.sql
notifier/deletions.py
notifier/notify.py
notifier/parsethread.py
notifier/timing.py
notifier/wikiconnection.py
tests/test_database.py

There are four channels:
* hourly
* daily
* weekly
* monthly
Of those, I am categorising weekly and monthly as 'infrequent'.
After the channel immediately preceding an infrequent channel (i.e. the hourly channel that runs an hour before it), any built-up notifications for users on that infrequent channel should be checked to see if those threads still exist (maybe even check posts individually, as a bonus).
(It occurs to me that it's probably worthwhile to only run this on the weekly channel rather than both the weekly and monthly channel.)
After the channel immediately following an infrequent channel, infrequent users should be checked to ensure that on the prior channel, they were actually notified. If not, they should be re-notified.
Although that being said... if the original …

Run tasks before and after infrequent channels

---

notifier/database/drivers/sqlite.py
notifier/database/queries/store_post.sql
notifier/database/queries/store_thread.sql
tests/test_database.py

SQLite runs in autocommit mode by default (which is temporarily turned off during an explicit transaction), but [Python's sqlite3 module](https://docs.python.org/3/library/sqlite3.html#sqlite3-controlling-transactions) does not - instead, it implicitly creates transactions around passed statements. It's sort of the same as what SQLite does in autocommit mode, except written in Python instead.
But there's a couple of places in notifier where I want to have control over that process. In particular in the following places:
https://github.com/croque-scp/notifier/blob/9d49216f2526eeaba8aea91858a981e68121cb31/notifier/database/drivers/sqlite.py#L69-L72
https://github.com/croque-scp/notifier/blob/9d49216f2526eeaba8aea91858a981e68121cb31/notifier/database/drivers/sqlite.py#L156-L160 …

Granular database control

---

.github/auth.ci.toml
.github/workflows/tests.yml
README.md
docs/database.md
notifier/database/queries/create_tables.script.sql

The latest version of MySQL supported by Amazon Aurora Serverless v1 is 5.6.10a. The current version as of the time of writing, and the version that is currently installed both on my computer and on GitHub Actions, is 8.0.26. I need to backdate both.
The closest version with an image available on Docker is 5.6.17. I can only hope that that's fine. If it turns out that it's not, the only thing I can do is make my own Docker image - I'd really rather not do that.
- I will likely have to use Docker for this.
Merges into #17

Pin MySQL version

---

notifier/config/user.py
notifier/database/drivers/mysql.py
notifier/database/queries/store_new_user_last_notified.sql
notifier/database/queries/store_new_user_timestamp.sql
notifier/parsethread.py
notifier/types.py
poetry.lock
pyproject.toml
tests/test_database.py

A user's timestamp is the timestamp of the post that they were last notified about, used to ensure that they are only ever notified about new posts made since then.
A user's initial timestamp is 0. This was to ensure that they'd be immediately caught up on all posts they missed from before they subscribed to the service. However, I quickly realise that this was a *terrible* idea, as it accrues *so many posts* for a user incredibly quickly. And I've only been running for about a day.
- The exact timestamp is not easy to get - not without compromising the current config getting method. But I don't need an exact timestamp - even just a date would be fine. I can get that via get_text easily.
In the future I would like to have a second default timestamp configured for the tool, and the highest …

Set initial user timestamp

---

README.md
notifier/cli.py
notifier/digest.py
notifier/notify.py

I need a test channel. When I run a sample execution on the command line, if I choose no channels, the bulk of the codebase will not execute. But if I choose any channel, I will notify users on that channel, which I don't want to do if I'm just testing.
A separate test channel should be created, used for testing. This will only notify users who want to be notified on the test channel (hopefully just me).
I should also add a dry run setting, which will be useful when I don't want to test the actual sending notifications bit.
Merges into #20 because I need this test there

Add a test channel

---

notifier/newposts.py
notifier/parsethread.py
notifier/types.py
notifier/wikiconnection.py

The module that I've been using `forum/ForumViewThreadModule` does 3 things:
1. It shows information about a thread (the thread header at the top of the page)
2. It shows information about the first page of a thread
3. If a post is specified, it shows information about the page of a thread containing that post
However, it is not paginated, which means it cannot be iterated over to get more posts. This is the cause of a fundamental issue in my procedure: I attempt to iterate this module to download the pages of a thread one-by-one, but because it does not support pagination, I actually download the first page of the thread as many times as there are pages in the thread. I noticed this by observing sets of posts being repeated in the download log (rather than by observing lots of missing …

Use forum posts module for iterating through posts

---

notifier/newposts.py
notifier/notify.py
pyproject.toml

If part of the procedure fails, the entire Lambda is aborted. That's not ideal.
Regardless of what actually causes the errors, unless it's something fundamental to the procedure, most errors should be caught, logged, discarded, and the process allowed to continue.
Broadly, that covers pretty much everything.

Group errors from sections of the procedure

---

notifier/main.py
notifier/timing.py

The current time, when it comes to checking which notification channels should be activated, is only checked once the notification process starts. However, there are things that can happen before that - for example, applying migrations to the database, which could take a long time. The current time needs to be cached as soon as possible.

Cache time instantly

---

notifier/config/user.py
notifier/deletions.py
notifier/notify.py
notifier/wikiconnection.py

I'd planned to use Wikidot's user profile's feature to ease moderation of the config site. However, after investigation, I discovered that these pages would be registered as having been created by 'Wikidot' (i.e. by no user), leading me unable to determine if the page had actually been created by the correct user; additionally, I would not be able to restrict editing of that page to that user only.
Instead I'm left with the brute-force option that I was dreading: systematic moderation.
I currently have the site set up so that any user can create any page in the `notify:` category, but only the user who created a page can edit it. Therefore, the only possible attack vector is malicious page creation - either in bulk, or targeting a specific user to cause them to be unable to configure …

Automatic moderation

---

.github/workflows/tests.yml
poetry.lock

Something's up with the CI - it keeps failing: 
```
Run poetry run pytest -x --notifier-config config.toml --notifier-auth .github/auth.ci.toml
poetry run pytest -x --notifier-config config.toml --notifier-auth .github/auth.ci.toml
shell: /usr/bin/bash -e {0}
env:
pythonLocation: /opt/hostedtoolcache/Python/3.8.12/x64
LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.12/x64/lib
VENV: .venv/bin/activate
The virtual environment found in /home/runner/work/notifier/notifier/.venv seems to be broken.
Recreating virtualenv notifier in /home/runner/work/notifier/notifier/.venv
FileNotFoundError
[Errno 2] No such file or directory: b'/snap/bin/pytest'
```
Seems like it might be something to do with the cache?

Fix CI tests

---

notifier/database/drivers/mysql.py

Was getting a persistent error on remote that I couldn't reproduce locally:
```
[ERROR] TypeError: can only concatenate list (not "tuple") to list
Traceback (most recent call last):
  File "/opt/python/lib/python3.8/site-packages/codeguru_profiler_agent/aws_lambda/profiler_decorator.py", line 52, in profiler_decorate
    return function(event, context)
  File "/opt/python/lib/python3.8/site-packages/codeguru_profiler_agent/aws_lambda/lambda_handler.py", line 51, in call_handler
    return handler_function(event, context)
  File "/var/task/lambda_function.py", line 38, in lambda_handler
    main(
  File "/var/task/notifier/main.py", line 54, in main
    notify(config, auth, channels, database)
  File "/var/task/notifier/notify.py", line 110, in notify
    notify_active_channels(
  File …
```

Fix automatic sub retrieval for user config construction

---

notifier/digest.py
notifier/lang.toml

The French SCP Wiki wants to be able to provide links to its own documentation page. It can do so by changing the `site` placeholder, but that placeholder assumes that it is the root of that site (instead of e.g. a single page of a site) by e.g. appending page names and anchors to it. Wikidot does not enable the creation of nested pages so this assumption is not valid. I can add the flexibility needed for translations to have control over the emitted links by adding more explicit placeholder for more granular override control.
Required for #35.

Use explicit placeholders for every link

---

README.md
notifier/cli.py
notifier/config/user.py
notifier/database/drivers/mysql.py
notifier/database/migrations/002-track-user-config-tags.down.sql
notifier/database/migrations/002-track-user-config-tags.up.sql
notifier/database/queries/get_user_configs_for_frequency.sql
notifier/database/queries/store_user_config.sql
notifier/main.py
notifier/newposts.py
notifier/notify.py
notifier/types.py
notifier/wikiconnection.py
tests/test_database.py
tests/test_digest.py

Configuration errors normally result in the user not being able to be notified of anything. Not being able to be notified means I'm unable to automatically notifiy them that they can't automatically be notified, so the user is never prompted to fix their config.
What I can do instead is edit their user config page to add a message explaining what the problem is and how to fix it, without any intervention from me. I can do this easily without compromising the data form by adding tags to the page. notifier can add these tags when it detects the error, not attempt to notify the user for as long as they're there, and remove the tags when the error is resolved.
Tags implemented so far:
* `restricted-inbox` - notifier failed to send a PM because the user has a restricted inbox.
* …

User config error tagging

---

README.md
notifier/digest.py
notifier/lang.toml
notifier/notify.py

[Requested by Wikidot user LORDXVNV](https://scp-wiki.wikidot.com/forum/t-14209085/forum-notifications-service#post-5116543):
> I do have a feature request, if possible: would it be viable to add 4/6/8 hour notification windows? I've found 1 hour to overfill my inbox but 24 hours to be so long that there's a good chance I've seen all the comments already.
Canonising the ID of this option as `8hourly`.

Add option to be notified every 8 hours

---

.devcontainer/devcontainer.json
Dockerfile
README.md
docker-compose.test.yml
docs/database.md
lambda_function.py
notifier/cli.py
notifier/database/drivers/base.py
notifier/database/drivers/mysql.py
notifier/database/queries/get_notifiable_users.sql
notifier/database/queries/get_posts_in_subscribed_threads.sql
notifier/database/queries/get_replies_to_subscribed_posts.sql
notifier/database/queries/get_user_ids_for_frequency_with_notifications.sql
notifier/emailer.py
notifier/main.py
notifier/notify.py
notifier/wikiconnection.py
tests/run_tests.sh
tests/test_database.py

Filter users before iterating for notification

---

README.md
config/auth.compose.toml
config/lang.toml
docker-compose.test.yml
docs/database.md
docs/deployment.md
notifier/database/drivers/mysql.py
notifier/database/migrations/001-track-first-post-id-per-thread.up.sql
notifier/database/queries/cache_post_context.sql
notifier/database/queries/get_user_ids_for_frequency_with_notifications.sql
notifier/digest.py
notifier/main.py
notifier/timing.py
tests/init.sql
tests/run_tests.sh

Resolves #62 
Then if everything looks good:
If everything works as expected:

Upgrade to MySQL 8

---

notifier/notify.py

Resolves #67
-----
The term 'error user' refers to a user with an error that prevents Notifier from contacting them. Currently the only conditions that cause that are
1. user wants PMs but inbox is closed and Notifier is not granted permission
2. user wants emails but Notifier can't access their email address
-----
Plan as per #67 is to take the count of missed notifications for a user and add it as a hidden tag to their user config page. Other pages on the site can then display that value natively.
The notification service will not be able to inform that user about the issue, but if the number is high enough, that can be enough to justify manual intervention; i.e.:
> "Please fix your config, you have X missed notifications"
is vastly preferable to
> "Please fix your config, you are …

Indicate missed notification count to error users

---

notifier/database/drivers/base.py
notifier/database/drivers/mysql.py
notifier/database/migrations/010-track-latest-timestamp-per-wiki.down.sql
notifier/database/migrations/010-track-latest-timestamp-per-wiki.up.sql
notifier/database/queries/delete_non_notifiable_posts.sql
notifier/database/queries/get_latest_post_timestamp.sql
notifier/database/queries/store_context_wiki.sql
notifier/database/queries/store_latest_post_timestamp.sql
notifier/newposts.py

2a85c2ce007d149e9974ab14d1e694a080ae6666 fixed a bug where a post would be skipped being downloaded if a post was stored with a later timestamp than it, which because posts are downloaded ordered by wiki and not by timestamp, was causing almost all posts to be skipped. It fixed it by limiting the 'latest timestamp' search only to posts from the given wiki.
While effective, this is not efficient. Most downloaded posts are deleted during the very same run, meaning on the next run, many of those same posts will be downloaded again, wasting time and networking resources.
This PR fixes this by recording the last time that posts were downloaded from a wiki in the context_wiki table. This recording will be permanent, even if the corresponding post is deleted.

Track last seen post timestamp per wiki

---

notifier/newposts.py
notifier/wikidot.py

During a wikibork, Wikidot will show an error page. I believe this is what is causing an error when trying to get a page ID, because I do not verify the content of the page before getting the ID, and receiving an error page means the request technically succeeded.
I need to work out how to reliably detect an error page before I can complete this.
Naive solution if I can't: page ID not in page AND some known error text present.
Countercase: theme:wikifot must not match.

Fail gracefully when getting a page during a bork

---

notifier/config/user.py
notifier/database/drivers/mysql.py
notifier/database/queries/delete_user_config.sql

Unsubscription is detected when a user is not returned in the config listpages. However, Wikidot occasionally fails to return some users from this query.
Marking users as being subscribed to the 'never' frequency effectively unsubscribes them, at the cost of their local config not being deleted should they delete their config from the config wiki.
As there is no longer a way to reliably detect this event, I consider this tradeoff to be necessary.
This resolves #116 by making the act of 'purging' user config non-destructive.

Mark unsubscribed users as freq=never
